---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljl.
--- DateTime: 2019/1/18 15:14
---
local ArenaData = BaseClass("ArenaData",Singleton)
local arena_victory_data = DataUtil.GetData("arena_message")
local function __init(self)
    ---竞技场宝箱数据
   self.arena_box_data = {}
    ---竞技场PK玩家数据
    self.pk_player_data = {}
    ---竞技场挑战对手的uid
    self.pk_player_uid = 0
    ---竞技场积分
    self.arena_score = 0
    ---竞技场刷新时间钻石花费金额
    self.timer_take_num = 0
    ---竞技场胜点
    self.arena_win_num = 0
    ---竞技场胜场
    self.arena_win_times = 0
    ---竞技场胜场总场数
    self.arena_all_times = 0
    ---购买的挑战券次数
    self.buy_tick_times = 0
    ---竞技场的排名
    self.arena_rank = 0
    ---区别白银还是黄金分数段
    self.rank_critical_score = 0
    ---可领取的宝箱id
    self.arena_has_boxes_id = {}
    ArenaData:GetInstance().rank_critical_score = arena_victory_data[1].RankCritical
end

--跨天刷新挑战次数
local function DayFlushIndication(self)
    local curTicket = BackpackData:GetInstance():GetItemNumById(1401007)
    if curTicket < arena_victory_data[1].InitTicket then
        BackpackData:GetInstance():UpdateItemData(1401007, arena_victory_data[1].InitTicket - curTicket)
    end
end

---打开竞技场,请求当前的段位信息
local function OpenArena(self)
    local get_arena_info_id = MsgIDDefine.PBARENA_GET_ARENA_INFO_REQUEST
    NetManager:GetInstance():SendMessage(get_arena_info_id,nil,function (msg_obj)
        if msg_obj.OpCode ~= 0 then
            Logger.Log("ERROR PBARENA_GET_ARENA_INFO_REQUEST~~")
            UISpecial:GetInstance():UITipText(msg_obj.Packages.msg)
            return
        else
            self.arena_player_data = msg_obj.Packages
            self.arena_score =  msg_obj.Packages.score
            UIManager:GetInstance():OpenWindow(UIWindowNames.UIArenaForChoice,self.arena_player_data)
        end
    end)
end

--发送单个竞技场数据
local function SendSinglArenaRequest(self,_isNotOpenLastPanel)
    local get_arena_info_id = MsgIDDefine.PBARENA_FLUSH_MATCH_REQUEST
    local get_arena_info = (MsgIDMap[get_arena_info_id])()
    get_arena_info.type = 0
    get_arena_info.rankType = 0
    NetManager:GetInstance():SendMessage(get_arena_info_id,get_arena_info,function (msg_obj)
        if msg_obj.OpCode ~= 0 then
            Logger.Log("ERROR PBARENA_FLUSH_MATCH_REQUEST~~")
            UISpecial:GetInstance():UITipText(msg_obj.Packages.msg)
            return
        else
            if UIManager:GetInstance():GetWindow(UIWindowNames.UIArenaForChoice,true,true) then
                UIManager:GetInstance():CloseWindow(UIWindowNames.UIArenaForChoice)
            end
            UIManager:GetInstance():OpenWindow(UIWindowNames.UIArenaMain,self.arena_player_data,msg_obj.Packages,_isNotOpenLastPanel)
        end
    end)
end

---请求竞技场刷新获取对手信息(从外界进来默认自动刷新)
local function OpenArenaOne(self,_isNotOpenLastPanel)
    if self.arena_player_data==nil then
        local get_arena_info_id = MsgIDDefine.PBARENA_GET_ARENA_INFO_REQUEST
        NetManager:GetInstance():SendMessage(get_arena_info_id,nil,function (msg_obj)
            if msg_obj.OpCode ~= 0 then
                Logger.Log("ERROR PBARENA_GET_ARENA_INFO_REQUEST~~")
                UISpecial:GetInstance():UITipText(msg_obj.Packages.msg)
                return
            else
                self.arena_player_data = msg_obj.Packages
                self.arena_score =  msg_obj.Packages.score
                SendSinglArenaRequest(self,_isNotOpenLastPanel);
            end
        end)
    else
        SendSinglArenaRequest(self,_isNotOpenLastPanel);
    end

end

ArenaData.OpenArena = OpenArena
ArenaData.OpenArenaOne =OpenArenaOne
ArenaData.DayFlushIndication = DayFlushIndication
ArenaData.__init = __init
return ArenaData