---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/8/5 18:05
---
local DanMuItem = BaseClass("DanMuItem", UIWrapComponent)
local base = UIWrapComponent
local Speed=8
local Height=-70
local CruHeight=30
local CurSecond=1
local function OnCreate(self,parent)
    base.OnCreate(self)
    self.parent=parent
    local rectTrans=UIUtil.FindComponent(CS.UnityEngine.GameObject.Find("UIRoot/InfoLayer").transform,typeof(CS.UnityEngine.RectTransform))
    self.sceen_width =rectTrans.sizeDelta.x
    self.sceen_height = rectTrans.sizeDelta.y
    self.text_info=self:AddComponent(UIText,"")
    self.text_pos=UIUtil.FindComponent(self.transform,typeof(CS.UnityEngine.RectTransform))
    self.text_obj=self.gameObject
    self.text_obj.gameObject:SetActive(false)
    self.can_set_data=true
end
local function OnRefresh(self,data,line)
    self.can_set_data=false
    self.text_obj.gameObject:SetActive(true)
    self.text_pos.sizeDelta.y=100
    self.text_info:SetText(data.info)
    self.speed=data.speed
    local width=self.text_info:GetPreferredWidth()
    local heigth=CruHeight+(line-1)*Height
    local move_speed=Speed*self.speed
    self.text_pos.anchoredPosition=Vector3.New(self.sceen_width/2+width/2,heigth,0)
    --开始滚动
    self.move_right=false
    self.move_left=false
    self.Timer=TimerManager:GetInstance():SimpleTimerArgs(1,function()
        self.text_pos.anchoredPosition=Vector3.New(self.text_pos.anchoredPosition.x-move_speed,heigth,0)
        if not self.move_right and self.text_pos.anchoredPosition.x<=self.sceen_width/2-width/2 then
            self.move_right=true
             TimerManager:GetInstance():SimpleTimerArgs(CurSecond,function()
                self.parent:SetItem(line)
            end,nil,true)
        end
        if not self.move_left and self.text_pos.anchoredPosition.x<-self.sceen_width/2-width/2 then
            if self.Timer ~= nil then
                TimerManager:GetInstance():SimpleTimerStop(self.Timer)
                self.Timer = nil
            end
            self:OnDisable()
        end
    end,nil,false,true)
end

local function OnDisable(self)
    if self.Timer ~= nil then
        TimerManager:GetInstance():SimpleTimerStop(self.Timer)
        self.Timer = nil
    end
    self.can_set_data=true
    self.text_obj.gameObject:SetActive(false)
    self.text_info:SetText("")
    self.text_pos.anchoredPosition=Vector3.New(2000,0,0)
end




DanMuItem.OnCreate = OnCreate
DanMuItem.OnRefresh = OnRefresh
DanMuItem.OnDisable = OnDisable

return DanMuItem