---
    --- Generated by EmmyLua(https://github.com/EmmyLua)
    --- Created by LJ095.
    --- DateTime: 2019/5/6 10:34
    ---

local UICardGLDingWei=BaseClass("UICardGLDingWei", UIBaseContainer);
local base = UIBaseContainer;

local keyname_path = "skillbg/base/keyname";
local desciable_path = "skillbg/next/next_Scroll/next_text";

local StaticCardData = DataUtil.GetData("card")
local StaticCardTagData = DataUtil.GetData("card_tag")

local function OnCreate(self,_holderSelf)
    base.OnCreate(self);
    self.parent=_holderSelf
    --定位关键词
    self.keynameText=self:AddComponent(UIText,keyname_path);
    self.desciableText=self:AddComponent(UIText,desciable_path);

    self:OnRefresh()

end



--刷新
local function OnRefresh(self)
    local cardData = StaticCardData[self.parent.cardId]
    local str = ""
    local num = #cardData.Tag
    for i = 1, num do
        str = str.."[".. StaticCardTagData[cardData.Tag[i]].Name .."]"
    end
    self.keynameText:SetText(str);
    self.desciableText:SetText(cardData.GuidDesc);
end


local function OnDestroy(self)
    base.OnDestroy(self)
end
local function OnDisable(self)

end
local function OnDestroy(self)
    --主界面DesTory 触发

end
UICardGLDingWei.OnDestroy= OnDestroy
UICardGLDingWei.OnDisable=OnDisable
UICardGLDingWei.OnCreate=OnCreate;
UICardGLDingWei.OnRefresh=OnRefresh;
UICardGLDingWei.OnDestroy=OnDestroy;
return UICardGLDingWei;