---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LJ095.
--- DateTime: 2019/6/13 17:05
---

local UICloseBtnComponent=BaseClass("UICloseBtnComponent", UIBaseContainer);
local base = UIBaseContainer;

local close_btn_path="BtnExit/BtnExit";
local return_main_btn_path="ReturnMainBtn/ReturnMainBtn";
local title_name_path="horizontalGrid/TitleName";
local help_btn_path="horizontalGrid/helpBtn";

local component_prb_path="UI/Prefabs/View/CloseBtnComponent.prefab"

local function OnCreate(self)
    base.OnCreate(self);
    self.closeBtn=self:AddComponent(UIButton,close_btn_path);
    self.closeBtn:SetOnClick(function()
        DataUtil.ExitAni(self.closeBtn,function ()
            if self.callback~=nil then
                self.callback();
            end
        end)
    end);
    self.returnMainBtn=self:AddComponent(UIButton,return_main_btn_path);
    self.returnMainBtn:SetOnClick(function()
        DataUtil.ExitAni(self.returnMainBtn,function ()
            if self.backMainCallback~=nil then
                self.backMainCallback();
            end
            if not self.notreturn then
                UIUtil.BackHomeMain();
            end

        end)
    end);
    self.titleText=self:AddComponent(UIText,title_name_path);
    self.helpBtn=self:AddComponent(UIButton,help_btn_path);
    self.helpBtn:SetOnClick(function()
        LJAudioManger:GetInstance():PlayVoice("UI_CommonClick")
        UIManager:GetInstance():OpenWindow(UIWindowNames.UICommonHelpInfo,self.helpDataId);
    end);
end

local function Refresh(self,_callback,_backMainCallback,_titleName,_isShowHelp,_helpDataId,notreturn)
    self.titleText:SetText(_titleName);
    self.callback=_callback;
    self.backMainCallback=_backMainCallback;
    self.helpBtn.transform.gameObject:SetActive(_isShowHelp);
    self.helpDataId=_helpDataId;
    self.notreturn=notreturn  --点击返回主城  不直接return
end


local function SetTitleData(self,title,helpID)
    if helpID then
        self.helpDataId=helpID;
    end
    self.titleText:SetText(title);
end
local function RecyleSelf(self)
    GameObjectPool:GetInstance():RecycleGameObject(component_prb_path,self.transform.gameObject);
    self:OnDestroy();
end

UICloseBtnComponent.OnCreate=OnCreate;
UICloseBtnComponent.Refresh=Refresh;
UICloseBtnComponent.RecyleSelf=RecyleSelf;
UICloseBtnComponent.SetTitleData=SetTitleData
return UICloseBtnComponent;