---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/10/16 21:10
---
local UINationNewBattleLogsTeamMsg = BaseClass("UINationNewBattleLogsTeamMsg", UIWrapComponent)
local base = UIWrapComponent

local UINationNewBattleLogsCardItem = require "UI.UINationNewBattleLogs.Component.UINationNewBattleLogsCardItem"
local cardListNum = 6
local function OnCreate(self,num1,num2,num3)
    base.OnCreate(self)
    -- 组件初始化
    self.model=self.view.model
    self.state_Img=self:AddComponent(UIImage,"EStateImg",AtlasConfig.DynamicNationTex)
    self.alliance_name=self:AddComponent(UIText,"EAllianceName")
    self.name=self:AddComponent(UIText,"EName")
    self.troops_slider=self:AddComponent(UISlider,"MyTroopsSlider")
    self.troops_slider_value_title=self:AddComponent(UIText,"MyTroopsSlider/MyTroopsValueTitle")
    self.troops_slider_value=self:AddComponent(UIText,"MyTroopsSlider/MyTroopsValue")
    self.troops_slider_value_title:SetText(DataUtil.GetClientText(200386))
    self.ItemList = {}
    for i = 1, cardListNum do
        self.ItemList[i] = UINationNewBattleLogsCardItem.New(self, "MyTeamIcon/MyCardIcon/Card"..i)
        self.ItemList[i]:OnCreate(self)
        self.ItemList[i]:SetActive(false)
    end
end

-- 组件被复用时回调该函数，执行组件的刷新
local function FlushContent(self,data,real_index)
   -- Logger.Log(real_index)
    self.alliance_name:SetText(data.unionName)
    self.troops_slider:SetValue(data.endArmy/data.startArmy)
    self.troops_slider_value:SetText(string.format("%d/%d",data.endArmy,data.startArmy))
    self.name:SetText(data.roleName)
    if data.isAttackCamp then
        self.state_Img:SetSpriteName("ui_t_c2_723")
    else
        self.state_Img:SetSpriteName("ui_t_c2_722")
    end
    for i = 1, cardListNum do
        if i<=table.length(data.cardIds) then
            self.ItemList[i]:FlushCardContent(data.cardData[i])
            self.ItemList[i]:SetActive(true)
        else
            self.ItemList[i]:SetActive(false)
        end
    end
end

UINationNewBattleLogsTeamMsg.OnCreate = OnCreate
UINationNewBattleLogsTeamMsg.FlushContent = FlushContent

return UINationNewBattleLogsTeamMsg