--[[
--note:

colums:
{ID,唯一键} ,{CardLevel,卡牌等级} ,{UnlockSkill,进阶到解锁的自身技能 0不解锁 1、2、3解锁对应序号技能} ,{UnlockSkillBlankAmount,进阶到解锁的技能栏 0不解锁 1、2、3解锁对应序号技能} ,{UnlockPersonalWeapon,进阶到解锁的专属武器0不解锁 1解锁}
primary key:
#0 [等级解锁]: ID
]]
return{
	[1] = {ID = 1,CardLevel = 1,UnlockSkill = {1,2},UnlockSkillBlankAmount = {1,2},UnlockPersonalWeapon = 1},
	[2] = {ID = 2,CardLevel = 2,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[3] = {ID = 3,CardLevel = 3,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[4] = {ID = 4,CardLevel = 4,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[5] = {ID = 5,CardLevel = 5,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[6] = {ID = 6,CardLevel = 6,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[7] = {ID = 7,CardLevel = 7,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[8] = {ID = 8,CardLevel = 8,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[9] = {ID = 9,CardLevel = 9,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[10] = {ID = 10,CardLevel = 10,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[11] = {ID = 11,CardLevel = 11,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[12] = {ID = 12,CardLevel = 12,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[13] = {ID = 13,CardLevel = 13,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[14] = {ID = 14,CardLevel = 14,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[15] = {ID = 15,CardLevel = 15,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[16] = {ID = 16,CardLevel = 16,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[17] = {ID = 17,CardLevel = 17,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[18] = {ID = 18,CardLevel = 18,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[19] = {ID = 19,CardLevel = 19,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[20] = {ID = 20,CardLevel = 20,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[21] = {ID = 21,CardLevel = 21,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[22] = {ID = 22,CardLevel = 22,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[23] = {ID = 23,CardLevel = 23,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[24] = {ID = 24,CardLevel = 24,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[25] = {ID = 25,CardLevel = 25,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[26] = {ID = 26,CardLevel = 26,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[27] = {ID = 27,CardLevel = 27,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[28] = {ID = 28,CardLevel = 28,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[29] = {ID = 29,CardLevel = 29,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[30] = {ID = 30,CardLevel = 30,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[31] = {ID = 31,CardLevel = 31,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[32] = {ID = 32,CardLevel = 32,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[33] = {ID = 33,CardLevel = 33,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[34] = {ID = 34,CardLevel = 34,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[35] = {ID = 35,CardLevel = 35,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[36] = {ID = 36,CardLevel = 36,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[37] = {ID = 37,CardLevel = 37,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[38] = {ID = 38,CardLevel = 38,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[39] = {ID = 39,CardLevel = 39,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[40] = {ID = 40,CardLevel = 40,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[41] = {ID = 41,CardLevel = 41,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[42] = {ID = 42,CardLevel = 42,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[43] = {ID = 43,CardLevel = 43,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[44] = {ID = 44,CardLevel = 44,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[45] = {ID = 45,CardLevel = 45,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[46] = {ID = 46,CardLevel = 46,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[47] = {ID = 47,CardLevel = 47,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[48] = {ID = 48,CardLevel = 48,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[49] = {ID = 49,CardLevel = 49,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[50] = {ID = 50,CardLevel = 50,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[51] = {ID = 51,CardLevel = 51,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[52] = {ID = 52,CardLevel = 52,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[53] = {ID = 53,CardLevel = 53,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[54] = {ID = 54,CardLevel = 54,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[55] = {ID = 55,CardLevel = 55,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[56] = {ID = 56,CardLevel = 56,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[57] = {ID = 57,CardLevel = 57,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[58] = {ID = 58,CardLevel = 58,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[59] = {ID = 59,CardLevel = 59,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0},
	[60] = {ID = 60,CardLevel = 60,UnlockSkill = {0},UnlockSkillBlankAmount = {0},UnlockPersonalWeapon = 0}
}