---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/8/8 11:56
---

local UIBiographyLeftWrapItem = BaseClass("UIBiographyLeftWrapItem", UIWrapComponent)
local base = UIWrapComponent

-- 组件添加了按钮组，则按钮被点击时回调该函数
local function OnBtnClick(self)
    LJAudioManger:GetInstance():PlayVoice("UI_CommonClick")
    self.view:SwitchLevel(self.index)
end

-- 创建
local function OnCreate(self)
    base.OnCreate(self)

    self.diBgImg = self:AddComponent(UIImage, "diBg", AtlasConfig.DynamicTex)
    self.iconImg = self:AddComponent(UIImage, "icon", AtlasConfig.DynamicTex)
    self.topBgImg = self:AddComponent(UIImage, "topBg", AtlasConfig.DynamicTex)
    self.qualityImg = self:AddComponent(UIImage, "quality", AtlasConfig.DynamicTex)
    self.nameText = self:AddComponent(UIText, "name")
    self.levelText = self:AddComponent(UIText, "levelbg/level")
    self.crystalImg = self:AddComponent(UIImage, "crystal", AtlasConfig.DynamicTex);
    self.crystalNumImg = self:AddComponent(UIText, "crystal/costSoulImg");
    self.chooseObj = UIUtil.FindTrans(self.transform, "chooseImage")
    self.starGroup = self:AddComponent(UIBaseContainer, "starGroup");
    self.starList = {};
    local starCount = self.starGroup.transform.childCount;
    for i = 0, starCount - 1 do
        local singleStarImg = self.starGroup:AddComponent(UIImage, i, AtlasConfig.DynamicTex);
        table.insert(self.starList, singleStarImg);
    end
    self.btn=self:AddComponent(UIButton,"")
    self.btn:SetOnClick(self,OnBtnClick)
end

-- 组件被复用时回调该函数，执行组件的刷新
local function OnRefresh(self, real_index)
    self.index = real_index + 1
    self.cardID = BiographyData:GetInstance()._cardIdGroup[self.index]
    local cardList = CardData:GetInstance().cards
    if self.cardID == nil or cardList[self.cardID] == nil then
        Logger.LogError("传记副本数据错误")
        return
    end
    self.chooseObj.gameObject:SetActive(self.index == self.view.selectLeftIndex)
    self.data = cardList[self.cardID];
    self.nameText.gameObject:SetActive(false);
    self.levelText:SetText(math.floor(self.data.level));
    self.topBgImg:SetSpriteName(SpriteDefine:GetCardTopFrameByQuality(self.data.quality))
    self.qualityImg:SetSpriteName(SpriteDefine:GetQuaIconByType(self.data.quality))
    self.iconImg:SetSpriteName(self.data.icon);
    self.crystalImg:SetSpriteName(SpriteDefine:GetCrystalIconByType(self.data.crystalType));
    self.crystalNumImg:SetText(math.floor(self.data.callCost));
    UIUtil.SetHeroStar(self.data.starlv, self.starList);
end

UIBiographyLeftWrapItem.OnCreate = OnCreate
UIBiographyLeftWrapItem.OnRefresh = OnRefresh

return UIBiographyLeftWrapItem