---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/9/10 19:49
---
local UIBiographyAwardListItem = BaseClass("UIBiographyAwardListItem", UIWrapComponent)
local base = UIWrapComponent

local UIBiographyAwardItem = require "UI.UIBiography.Component.UIBiographyAwardItem"

local function SetActive(self, isActive)
    self.transform.gameObject:SetActive(isActive)
end

local function OnCreate(self)
    base.OnCreate(self)
    self.titleText = self:AddComponent(UIText, "tip_1/chooseTip")
    self.closeBtn=self:AddComponent(UIButton,"closeBtn");
    self.closeBtn:SetOnClick(function()
        LJAudioManger:GetInstance():PlayVoice("UI_Cancel")
        SetActive(self, false)
    end)
    self.maskBtn=self:AddComponent(UIButton,"maskBtn");
    self.maskBtn:SetOnClick(function()
        LJAudioManger:GetInstance():PlayVoice("UI_Cancel")
        SetActive(self, false)
    end)
    SetActive(self, true)
    self.wrapgroup = self:AddComponent(UIWrapGroup3D, "chooseScrollView/chooseGroup", UIBiographyAwardItem);
    SetActive(self, false)
end

local function OnEnable(self)
    base.OnEnable(self);
end
local function SetData(self, levelIndex)
    self.cardID = BiographyData:GetInstance()._cardIdGroup[self.view.selectLeftIndex]
    self.data = BiographyData:GetInstance()._data[self.cardID][levelIndex]
    self.view.lookLevelIndex = levelIndex
    if self.data.KeyDropShow == nil then
        Logger.LogError("传记副本奖励为空")
        return
    end
    SetActive(self, true)
    self.titleText:SetText(string.format(DataUtil.GetClientText(100137), self.data.Name))
    self.wrapgroup:SetLength(table.count(self.data.KeyDropShow))
    self.wrapgroup:ResetToBeginning()
end

UIBiographyAwardListItem.OnCreate = OnCreate;
UIBiographyAwardListItem.OnEnable=OnEnable;
UIBiographyAwardListItem.SetData =SetData;
UIBiographyAwardListItem.SetActive = SetActive;
return UIBiographyAwardListItem;