---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LJ095.
--- DateTime: 2019/5/22 13:47
---

local UILevelNewDetailModel = BaseClass("UILevelNewDetailModel", UIBaseModel)
local base = UIBaseModel

local function OnCreate(self)
    base.OnCreate(self)
    -- 窗口生命周期内保持的成员变量放这

end

-- 打开
local function OnEnable(self,leveldata,_isRebindScene)
    base.OnEnable(self)
    self.isRebindScene=_isRebindScene;
    self.data = leveldata;
    self.playLv=UserData:GetInstance().pLevel
    self.starList={};
    local tbstardex = DataUtil.GetData("star_rule");
    for i = 1, 3 do
        local id = leveldata._data.StarRating[i]
        local status = {}

        if leveldata._star == 0 then
            status[1] = 0
        elseif leveldata._star == 3 then
            status[1] = 1
        else
            if leveldata._StarIds[id] ~= nil then
                status[1] = 1
            else
                status[1] = 0
            end
        end
        status[2] = tbstardex[id]
        table.insert(self.starList,status);
    end
    self.itemList={};
    local expId=1401014;
    local expXlsx=DataUtil.GetDataByIdAndType(expId);
    local expVal=self.data._data.FirstExp;
    table.insert(self.itemList,{xlsxData=expXlsx,val=expVal});
    if self.data._data.FDAward ~= nil then
        for i, v in ipairs(self.data._data.FDAward) do
            local itemXlsxData= DataUtil.GetDataByIdAndType(v.Id);
            local val=v.Val;
            table.insert(self.itemList,{xlsxData=itemXlsxData,val=val});
        end
    end

end



UILevelNewDetailModel.OnCreate = OnCreate
UILevelNewDetailModel.OnEnable = OnEnable

return UILevelNewDetailModel