---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/5/30 15:13
local TeachTipItem = BaseClass("TeachTipItem", UIBaseContainer)
local base = UIBaseContainer
local function OnCreate(self,holder)
    base.OnCreate(self)
    self.holder=holder
    self.black1=UIUtil.FindTrans(self.transform,"black1")
    self.black2 =UIUtil.FindTrans(self.transform,"black2")
    self.text=self:AddComponent(UIText,"Text")

end
--[[
int GetLineCount()
{
    Text tex = GetComponent<Text>();
    string strText = tex.text;
    tex.text = "";
float linrHeight = tex.preferredHeight;
tex.text = strText;

return (int)(tex.preferredHeight / height);
}
--]]
local function GetRowNum(self,Str)
    self.text:SetText("")
    local height=self.text:GetPreferredHeight()
    self.text:SetText(Str)
    local allheight=self.text:GetPreferredHeight()
    return math.floor(allheight/ height)
end
local function OnRefresh(self,content,upbase)
    --如果事true   第一个底黑色
    --self.text:SetText(content)
    --local heigth=self.text:GetPreferredHeight()
    self.Row= self:GetRowNum(content)
    if upbase then
        self.black1.gameObject:SetActive(true)
        self.black1.transform.localPosition=Vector3.New(0,0,0)
        if self.Row>=3 then
            self.black2.gameObject:SetActive(true)
            self.black2.transform.localPosition=Vector3.New(0,-92,0)
        else
            self.black2.gameObject:SetActive(false)
        end
    else
        if self.Row>=2 then
            self.black1.gameObject:SetActive(true)
            self.black1.transform.localPosition=Vector3.New(0,-46,0)
            if self.Row>=4 then
                self.black2.gameObject:SetActive(true)
                self.black2.transform.localPosition=Vector3.New(0,-138,0)
            else
                self.black2.gameObject:SetActive(false)
            end
        else
            self.black1.gameObject:SetActive(false)
            self.black2.gameObject:SetActive(false)
        end
    end
    local t1, t2 = math.modf(self.Row/2)
    if upbase and t2==0 then
        self.nextbase=true
    elseif not upbase and t2>0 then
        self.nextbase=true
    else
        self.nextbase=false
    end
end

local function OnDisable(self)


end

TeachTipItem.OnRefresh = OnRefresh
TeachTipItem.OnCreate = OnCreate
TeachTipItem.OnDisable=OnDisable
TeachTipItem.GetRowNum = GetRowNum
return TeachTipItem