---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/5/16 14:56
local UICardTalentTipView = BaseClass("UICardTalentTipView", UIBaseView)
local base = UIBaseView


--提示框

local tip_close_btn_path="ParentLayout/Close_Des_Btn";
local tip_title_text_path="ParentLayout/destext";
local tip_content_text_path="ParentLayout/destest_text";
local function OnCreate(self)
    base.OnCreate(self)
    --提示框
    self.tipCloseBtn=self:AddComponent(UIButton,tip_close_btn_path);
    self.tipCloseBtn:SetOnClick(function()
        LJAudioManger:GetInstance():PlayVoice("UI_Cancel")
        UIManager:GetInstance():CloseWindow(UIWindowNames.UICardTalentTip);
    end)
    self.CloseBtn=self:AddComponent(UIButton,"ParentLayout/Image");
    self.CloseBtn:SetOnClick(function()
        LJAudioManger:GetInstance():PlayVoice("UI_Cancel")
        UIManager:GetInstance():CloseWindow(UIWindowNames.UICardTalentTip);
    end)
    --self.tipTitleText=self:AddComponent(UIText,tip_title_text_path);
    self.tipContentText=self:AddComponent(UIText,tip_content_text_path);
end

local function OnEnable(self)
    base.OnEnable(self);
    --设置提示框数据
    --self.tipTitleText:SetText(self.model.cardName.."星级特质说明")
    --self.tipContentText:SetText(self.model.tipInfo);
end

UICardTalentTipView.OnCreate = OnCreate;
UICardTalentTipView.OnEnable=OnEnable;

return UICardTalentTipView;