---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljl.
--- DateTime: 2019/7/1 17:49
---
local UIGetNewCardWrapItem = BaseClass("UIGetNewCardWrapItem", UIWrapComponent)
local base = UIWrapComponent



--设置背景

-- 组件添加了按钮组，则按钮被点击时回调该函数
local function OnClick(self)
    LJAudioManger:GetInstance():PlayVoice("UI_CommonClick")
    if not self.data.isSelect then
        DataManager:GetInstance():Broadcast(DataMessageNames.ON_CARD_POOL_SELECT, self.data.xlsxData.ID)
    end
end
-- 创建
local function OnCreate(self)
    base.OnCreate(self)
    self.icon=self:AddComponent(UIImage,"iconImg",AtlasConfig.DynamicTex)
    self.btn = self:AddComponent(UIButton,"BG")
    self.nameText=self:AddComponent(UIText,"Title")
    self.selectObj = UIUtil.FindTrans(self.transform,"Select")
    self.btn:SetOnClick(OnClick,self)
    self.sliderImg=self:AddComponent(UIImage,"slider/sliderImg",AtlasConfig.DynamicTex);
    self.sliderVal=self:AddComponent(UIText,"slider/sliderVal")
end

-- 组件被复用时回调该函数，执行组件的刷新
local function OnRefresh(self, real_index)
    self.dataIndex=real_index+1
    self.data = self.view.cardList[self.dataIndex]
    local bugItemData=DataUtil.GetDataByIdAndType(self.data.xlsxData.BugItem.ID);
    self.nameText:SetText(string.format(self.data.xlsxData.DrawDesc,self.data.xlsxData.BugItem.Num,bugItemData.name))
    self.icon:SetSpriteName(self.data.xlsxData.PageSign,nil,nil,function ()
        if self.transform.name == "0" then
            --加载好了 可以开启引导丑卡
            if GuideGroup:GetInstance().Runing  then
                DataManager:GetInstance():Broadcast(DataMessageNames.UI_Guide_NeedEvent)
            end
        end
    end)
    self.sliderVal:SetText(string.format("%s/%s",math.floor(self.data.val),self.data.xlsxData.LuckyPointLimit));
    self.selectObj.gameObject:SetActive(self.data.isSelect)
    local fieldVal=self.data.val/self.data.xlsxData.LuckyPointLimit;
    self.sliderImg:SetFillVal(fieldVal);
end



UIGetNewCardWrapItem.OnCreate = OnCreate
UIGetNewCardWrapItem.OnRefresh = OnRefresh
return UIGetNewCardWrapItem