---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guoyu.
--- DateTime: 2018/11/7 15:55
---
local StoryBattleNetManager=BaseClass("StoryBattleNetManager")
local MsgIDDefine = require "Net.Config.MsgIDDefine"
local MsgIDMap = require "Net.Config.MsgIDMap"
local BattleFieldManager=require "GameLogic.BattleNew.Logic.Manager.BattleFieldManager"
local function __init(self)

    --事件
    self.battleMessage=nil
end


function StoryBattleNetManager:SendPveBattleStartRequest(func)
    ResourcesManager:GetInstance():LoadAsync(BattleFieldManager:GetInstance().battlePath.."pve_start_response.txt",typeof(CS.UnityEngine.TextAsset),function(asset)
        local protoSourceData = (MsgIDMap[MsgIDDefine.PBFIGHT_PVE_START_RESPONSE])
        local msg_obj = protoSourceData()
        msg_obj:ParseFromString(asset.bytes)
        if func ~= nil then
            func(msg_obj)
        end
    end)
end

function StoryBattleNetManager:SendConvertCrytalsRequest(round,func)
    ResourcesManager:GetInstance():LoadAsync(BattleFieldManager:GetInstance().battlePath..round.."_convert_crytals_response.txt",typeof(CS.UnityEngine.TextAsset),function(asset)
        local protoSourceData = (MsgIDMap[MsgIDDefine.PBFIGHT_CONVERT_CRYTALS_RESPONSE])
        local msg_obj = protoSourceData()
        msg_obj:ParseFromString(asset.bytes)
        if func ~= nil then
            func(msg_obj)
        end
    end)
end

function StoryBattleNetManager:SendPveActionRequest(round,func)
    Logger.Log("发送战斗回合数据")
    ResourcesManager:GetInstance():LoadAsync(BattleFieldManager:GetInstance().battlePath..round.."_pve_action_response.txt",typeof(CS.UnityEngine.TextAsset),function(asset)
        local protoSourceData = (MsgIDMap[MsgIDDefine.PBFIGHT_PVE_ACTION_RESPONSE])
        local msg_obj = protoSourceData()
        msg_obj:ParseFromString(asset.bytes)
        if func ~= nil then
            func(msg_obj)
        end
    end)
end

StoryBattleNetManager.__init=__init
return StoryBattleNetManager