---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LJ095.
--- DateTime: 2019/9/21 15:56
---
local UIScreenShake = BaseClass("UIScreenShake", Updatable)

local offestVal_X=1;--相机最大偏差值,左右
local offestVal_Y=2;--相机最大偏差值，上下
local maxRotateRate = Mathf.PI;--最大倾斜角
local targetTransPos=nil;
local sensitivity=7;
local function OnCreate(self, _transform)
    self.transform=_transform;
    local transPos=self.transform.localPosition;
    self.pos=Vector3.New(transPos.x,transPos.y,transPos.z);
    --print("当前相机的位置是",self.pos);
    targetTransPos=transPos;
    --base.EnableUpdate(true)
end

local function Update(self)
    if self.transform==nil then
        return;
    end
    local m_MobileOrientation=CS.UnityEngine.Input.acceleration;
    targetTransPos.x=self.transform.localPosition.x + m_MobileOrientation.x*sensitivity;
    targetTransPos.z = self.transform.localPosition.z +m_MobileOrientation.y*sensitivity;
    targetTransPos.x = targetTransPos.x-self.pos.x> offestVal_X  and  self.pos.x+offestVal_X or targetTransPos.x;
    targetTransPos.x = targetTransPos.x-self.pos.x <-offestVal_X and self.pos.x-offestVal_X or targetTransPos.x;
    targetTransPos.z = targetTransPos.z-self.pos.z> offestVal_Y  and  self.pos.z+offestVal_Y or targetTransPos.z;
    targetTransPos.z = targetTransPos.z-self.pos.z <-offestVal_Y and self.pos.z-offestVal_Y or targetTransPos.z;
    self.transform.localPosition= Vector3.Lerp(self.transform.localPosition, targetTransPos, Time.deltaTime * sensitivity);;
    --print("当前相机的位置是",self.pos,"最终位置",targetTransPos);
end


UIScreenShake.Update=Update;
UIScreenShake.OnCreate = OnCreate

return UIScreenShake;