---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljl.
--- DateTime: 2019/3/11 15:36
---
local LevelAwardItem = BaseClass("LevelAwardItem", UIBaseContainer)
local base = UIBaseContainer


local function OnCreate(self)
    base.OnCreate(self)
    self.info_icon = self:AddComponent(UIImage,"iconImg",AtlasConfig.DynamicTex)
    self.info_frame = self:AddComponent(UIImage,"",AtlasConfig.DynamicTex)
    self.info_num = self:AddComponent(UIText,"number_UIText")
    local info_iconPress=self:AddComponent(UIEventTrigger,"iconImg");
    info_iconPress:SetOnLongPress(function()
        if self.item_data.type==20 or self.item_data.type==21 then
            local serverData=EquipData:GetInstance().equipList[self.item_data.id];
            if serverData ~= nil then
                UIManager:GetInstance():OpenWindow(UIWindowNames.UICardEquipmentProp,0,self.item_data.id,true);
            else
                UIManager:GetInstance():OpenWindow(UIWindowNames.UIItemTips,self.item_data.id)
            end
        else
            UIManager:GetInstance():OpenWindow(UIWindowNames.UIItemTips,self.item_data.id)
        end
    end,(function()
        if self.item_data.type==20  or self.item_data.type==21then
            local serverData=EquipData:GetInstance().equipList[self.item_data.id];
            if serverData ~= nil then
                UIManager:GetInstance():CloseWindow(UIWindowNames.UICardEquipmentProp)
            else
                UIManager:GetInstance():CloseWindow(UIWindowNames.UIItemTips)
            end
        else
            UIManager:GetInstance():CloseWindow(UIWindowNames.UIItemTips)
        end
    end),true)
end
local function SetData(self,itemData)
    self.item_data = itemData
    if self.item_data.type ==20 or  self.item_data.type ==21 then
        self.info_frame:SetSpriteName(SpriteDefine:GetCircleFrameByType(itemData.Quality))
    else
        self.info_frame:SetSpriteName(SpriteDefine:GetItemQualityFrameByType(itemData.Quality))
    end


    self.info_icon:SetSpriteName(itemData.icon)
    self.info_num:SetText(itemData.num)
end
--刷新
local function Refresh(self,itemData)

end
LevelAwardItem.OnCreate=OnCreate
LevelAwardItem.Refresh=Refresh
LevelAwardItem.SetData = SetData
return LevelAwardItem