---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by aaa.
--- DateTime: 2019/2/28 9:44
---

local UIFriendPlayerWrap = BaseClass("UIBaseContainer", UIBaseContainer)
local itemData = DataUtil.GetData("item")
local base = UIBaseContainer

local function ClickBtn(self,force_voice)
    if not force_voice then
        LJAudioManger:GetInstance():PlayVoice("UI_CommonClick")
    end
    if self.holder.last_index ~= self.index then
        if self.holder.last_item then
            self.holder.last_item:SetSpriteName("ui_t_c2_066")
        end
        self.holder.last_index = self.index
        self.bg:SetSpriteName("ui_t_c2_071")
        self.holder.last_item = self.bg
        self.holder:UpdatePlayerData(self.index)
        self.red_game:SetActive(false)
    end
end


-- 创建
local function OnCreate(self,holder)
    base.OnCreate(self)
    self.frame = self:AddComponent(UIImage,"frame",AtlasConfig.DynamicTex)
    self.icon = self:AddComponent(UIImage,"icon",AtlasConfig.DynamicTex)
    self.name_text = self:AddComponent(UIText,"name")
    self.lv_text = self:AddComponent(UIText,"LvFrame/leftlv")
    self.state_text = self:AddComponent(UIText,"state")
    self.bg = self:AddComponent(UIImage,"bg/bg (1)",AtlasConfig.DynamicTex)
    self.btn = self:AddComponent(UIButton,"bg")
    self.btn:SetOnClick(self,ClickBtn)
    self.btnIcon = self:AddComponent(UIButton,"frame")
    local bindfunc=Bind(self,function()  ClickBtn(self);holder.OpenBtnFunctionWindow(holder) end)
    self.btnIcon:SetOnClick(bindfunc)
    self.holder = holder
    self.red_game = UIUtil.FindTrans(self.transform,"redpoint").gameObject
end

local function GetTimeStr(last_time)
    local time = TimeSyncManager:GetInstance():GetSimulationJavaMS()/1000 - last_time
    if time > 86400 then
        return math.ceil(time/86400).."天前"
    elseif time > 3600 then
        return math.ceil(time/3600).."小时前"
    elseif time >= 60 then
        return math.ceil(time/60).."分钟前"
    elseif time<60 then
        return "一分钟前"
    end
end

-- 组件被复用时回调该函数，执行组件的刷新
local function OnRefresh(self, real_index, check)
    local data =self.holder:GetPlayerDataById(self.holder.left_list[real_index+1])
    if data == nil then
        return
    end
    self.index = real_index+1
    self.name_text:SetText(data.name)
    self.lv_text:SetText(data.lv)
    self.icon:SetSpriteName(itemData[data.head].Icon)
    self.frame:SetSpriteName(SpriteDefine:GetItemQualityFrameByType(itemData[data.head].Quality))
    --self.icon:SetSpriteName(itemData[data.head].Icon)
    --self.frame:SetSpriteName(SpriteDefine:GetItemQualityFrameByType(itemData[data.head].Quality))
    if data.state == 1 then
        self.state_text:SetText("在线")
        self.state_text:SetColor32(79,152,54,255)
        self.red_game:SetActive(RedPointData:GetInstance():GetRedState("friend_friend_friend_"..data.id))
    else
        self.state_text:SetText(GetTimeStr(data.last_login_time))
        self.state_text:SetColor32(0,0,0,255)
        self.red_game:SetActive(RedPointData:GetInstance():GetRedState("friend_friend_stranger_"..data.id))
    end

    if self.holder.last_index == self.index then
        --self.bg:SetColor32(168,168,168,50)
    else
        --self.bg:SetColor32(0,0,0,212)
    end

end
local function OnInit(self)

    if self.index == 1 then
        self.holder.last_index = -1
        ClickBtn(self,true)
    end
end
UIFriendPlayerWrap.OnInit = OnInit
UIFriendPlayerWrap.OnRefresh = OnRefresh
UIFriendPlayerWrap.OnCreate = OnCreate

return UIFriendPlayerWrap