---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljl.
--- DateTime: 2019/3/1 16:17
---
local UINoticeWrapItem=BaseClass("UINoticeWrapItem",UIWrapComponent)
local base = UIWrapComponent



local function OnCreate(self)
    base.OnCreate(self)
    --组建初始化
    self.btn = self:AddComponent(UIButton, "Image")
    self.btn:SetOnClick(function ()
         self.view:SetContData(self.single_data)
        --TODO:将自身的按钮背景进行更改，字体颜色以及描边进行修改
    end)
    self.name_text = self:AddComponent(UIText, "Image/name")
    self.new_obj =  UIUtil.FindTrans(self.transform,"Image/newImg")
    self.new_obj = self:AddComponent(UIImage,"Image/newImg",AtlasConfig.DynamicTex)
end
local function OnUpdate(self,y)
    local final =(395-y)/5.73+60
    self.btn.rectTransform.anchoredPosition=Vector3.New(final,0,0)
end
-- 组件被复用时回调该函数，执行组件的刷新
local function OnRefresh(self,real_index)
    local data=self.view.data_list[real_index+1]
    self.single_data = data
    if data==nil then
        return
    end
    self.name_text:SetText(data.name)
end

UINoticeWrapItem.OnCreate = OnCreate
UINoticeWrapItem.OnRefresh=OnRefresh
UINoticeWrapItem.OnUpdate=OnUpdate

return UINoticeWrapItem