---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljl.
--- DateTime: 2019/2/23 13:52
---
local DailyActiveWrapItem=BaseClass("DailyActiveWrapItem",UIWrapComponent)
local base = UIWrapComponent

local function OnCreate(self)
    base.OnCreate(self)
    --组建初始化
    self.icon_img = self:AddComponent(UIImage, "iconImage", AtlasConfig.DynamicTex)
    self.btn = self:AddComponent(UIButton, "diImg")
    self.btn:SetOnClick(function ()
        self.view:SetAwardShow(self.single_data)
    end)
    self.comeBtn = self:AddComponent(UIButton,"comeBtn")
    self.comeBtn:SetOnClick(function ()
        UISpecial:GetInstance():UITipText("跳转功能暂未开放！")
    end)
    self.name_text = self:AddComponent(UIText, "titleText")
    self.des_text = self:AddComponent(UIText,"desText")
    self.info_img1 = self:AddComponent(UIImage,"infoImg1",AtlasConfig.DynamicTex)
    self.info_text1 = self:AddComponent(UIText,"infoImg1/Text1")
    self.info_img2 = self:AddComponent(UIImage,"infoImg2",AtlasConfig.DynamicTex)
    self.info_text2 = self:AddComponent(UIText,"infoImg2/Text2")
    self.info_img3 = self:AddComponent(UIImage,"infoImg3",AtlasConfig.DynamicTex)
    self.info_text3 = self:AddComponent(UIText,"infoImg3/Text3")
end

-- 组件被复用时回调该函数，执行组件的刷新
local function OnRefresh(self,real_index)
    local data=self.view.daily_active_data[real_index+1]
    self.single_data = data
    if data==nil then
        return
    end
    --self.icon_img:SetSpriteName(data.task_icon)
    self.name_text:SetText(data.task_name)
    self.des_text:SetText(data.task_des)
    if data.task_param ~= nil and table.count(data.task_param) ==1 then
        self.info_img1.gameObject:SetActive(true)
        self.info_img2.gameObject:SetActive(false)
        self.info_img3.gameObject:SetActive(false)
        --self.info_img1:SetSpriteName(data.task_param[1].pic)
        self.info_text1:SetText(data.task_param[1].class)
    elseif table.count(data.task_param) == 2 then
        self.info_img1.gameObject:SetActive(true)
        self.info_img2.gameObject:SetActive(true)
        self.info_img3.gameObject:SetActive(false)
        --self.info_img1:SetSpriteName(data.task_param[1].pic)
        self.info_text1:SetText(data.task_param[1].class)
        --self.info_img2:SetSpriteName(data.task_param[2].pic)
        self.info_text2:SetText(data.task_param[2].class)
    elseif table.count(data.task_param) == 3 then
        self.info_img1.gameObject:SetActive(true)
        self.info_img2.gameObject:SetActive(true)
        self.info_img3.gameObject:SetActive(true)
        --self.info_img1:SetSpriteName(data.task_param[1].pic)
        self.info_text1:SetText(data.task_param[1].class)
        --self.info_img2:SetSpriteName(data.task_param[2].pic)
        self.info_text2:SetText(data.task_param[2].class)
        --self.info_img3:SetSpriteName(data.task_param[3].pic)
        self.info_text3:SetText(data.task_param[3].class)
    end
end

DailyActiveWrapItem.OnCreate = OnCreate
DailyActiveWrapItem.OnRefresh=OnRefresh

return DailyActiveWrapItem