---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljl.
--- DateTime: 2019/3/11 15:36
---
local TaskAwardItem = BaseClass("TaskAwardItem", UIBaseContainer)
local base = UIBaseContainer


local function OnCreate(self)
    base.OnCreate(self)
    self.frame_Img =self:AddComponent(UIImage,"",AtlasConfig.DynamicTex)
    self.icon_Img = self:AddComponent(UIImage,"awardIcom1",AtlasConfig.DynamicTex)
    self.count_Text = self:AddComponent(UIText,"count1")
    self.info_iconPress=self:AddComponent(UIEventTrigger,"")
    self.info_iconPress:SetOnLongPress(function()
        UIManager:GetInstance():OpenWindow(UIWindowNames.UIItemTips,self.item_data.id)
    end,(function()
        UIManager:GetInstance():CloseWindow(UIWindowNames.UIItemTips)
    end),true)
end

--刷新
local function Refresh(self,itemData)
    self.item_data = itemData
    if itemData == nil then
        return
    end
    if self.item_data.type==20  or  self.item_data.type==21 then
        self.frame_Img:SetSpriteName(SpriteDefine:GetCircleFrameByType (self.item_data.quality))
    else
        self.frame_Img:SetSpriteName(SpriteDefine:GetItemQualityFrameByType (self.item_data.quality))
    end
    self.count_Text:SetText(itemData.num)
    self.icon_Img:SetSpriteName(itemData.icon)
end
TaskAwardItem.OnCreate=OnCreate
TaskAwardItem.Refresh=Refresh
return TaskAwardItem