---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LJ095.
--- DateTime: 2019/4/22 14:59
---

local UINationEnterAlianceWrapItem = BaseClass("UINationEnterAlianceWrapItem", UIWrapComponent)
local base = UIWrapComponent

local name_path = "AlianceName";
local lv_path = "AlianceLv";
local member_path = "AlianceMemberNum";
local area_path = "AlianceArea";
local ligeance_path = "AlianceLigeance";
local shili_value_path = "AlianceShiLiValue";
local can_not_apply_path = "CannotApply";
local apply_btn_path = "applyBtn";
local cancel_apply_btn_path = "cancelBtn";
local enter_btn_path = "enterBtn";

local function OnCreate(self)
    base.OnCreate(self)
    self.bgImg = self:AddComponent(UIImage, "bg");
    self.bgButton = self:AddComponent(UIButton, "");
    self.bgButton:SetOnClick(function()
        LJAudioManger:GetInstance():PlayVoice("UI_CommonClick");
        -- 打开联盟详情
        UIManager:GetInstance():OpenWindow(UIWindowNames.UINationAlianceDetail, self.singleData);
    end)
    self.nameText = self:AddComponent(UIText, name_path);
    self.lvText = self:AddComponent(UIText, lv_path);
    self.memberText = self:AddComponent(UIText, member_path);
    self.areaText = self:AddComponent(UIText, area_path);
    self.ligeanceText = self:AddComponent(UIText, ligeance_path);
    self.shiliValueText = self:AddComponent(UIText, shili_value_path);
    self.canNotApplyText = UIUtil.FindTrans(self.transform, can_not_apply_path);
    self.applyBtn = self:AddComponent(UIButton, apply_btn_path);
    self.applyBtn:SetOnClick(function()
        LJAudioManger:GetInstance():PlayVoice("UI_CommonClick");
        self.view.ctrl:SendNationApplyUnionRequest(self.singleData)
    end)
    self.cancelBtn = self:AddComponent(UIButton, cancel_apply_btn_path);

    self.cancel_btn_text = self:AddComponent(UIText, "cancelBtn/CancelText")--取消申请
    self.apply_btn_text = self:AddComponent(UIText, "applyBtn/ApplyText")--申请
    self.enter_btn_text = self:AddComponent(UIText, "enterBtn/EnterText")--加入

    self.cancelBtn:SetOnClick(function()
        LJAudioManger:GetInstance():PlayVoice("UI_CommonClick");
        self.view.ctrl:SendNationApplyUnionRequest(self.singleData)
    end);
    self.enterBtn = self:AddComponent(UIButton, enter_btn_path);
    self.enterBtn:SetOnClick(function()
        LJAudioManger:GetInstance():PlayVoice("UI_CommonClick");
        self.view.ctrl:SendNationApplyUnionRequest(self.singleData)
    end)
end

-- 组件被复用时回调该函数，执行组件的刷新
local function OnRefresh(self, real_index)
    self.bgImg:SetEnabled((real_index + 1) % 2 == 0);
    self.dataIndex = real_index + 1
    local singleData = self.view.model.alianceList[self.dataIndex];
    self.singleData = singleData
    self.nameText:SetText(singleData.name);
    self.lvText:SetText(singleData.level);
    self.memberText:SetText(string.format("%s/%s", singleData.members, singleData.currentNationalUnionLevelData.Member));
    self.areaText:SetText(singleData.regionData.Name);
    self.ligeanceText:SetText(singleData.citys);
    self.shiliValueText:SetText(singleData.force);
    self.cancel_btn_text:SetText(DataUtil.GetClientText(200089))
    self.apply_btn_text:SetText(DataUtil.GetClientText(200090))
    self.enter_btn_text:SetText(DataUtil.GetClientText(200091))

    if singleData.isApply then
        self.canNotApplyText.gameObject:SetActive(false);--不可申请文字
        self.applyBtn.gameObject:SetActive(false);--申请
        self.cancelBtn.gameObject:SetActive(true);--取消申请
        self.enterBtn.gameObject:SetActive(false); -- 加入
    else
        self.cancelBtn.gameObject:SetActive(false);--取消申请
        if singleData.apply == NationDefine.NATION_UNION_APPLY_SETTING.CLOSE_APPLY then
            self.canNotApplyText.gameObject:SetActive(true);--不可申请文字
            self.applyBtn.gameObject:SetActive(false);--申请
            self.cancelBtn.gameObject:SetActive(false);--取消申请
            self.enterBtn.gameObject:SetActive(false); -- 加入
        elseif singleData.apply == NationDefine.NATION_UNION_APPLY_SETTING.ANY_PERSON then
            self.canNotApplyText.gameObject:SetActive(false);--不可申请文字
            self.applyBtn.gameObject:SetActive(false);--申请
            self.cancelBtn.gameObject:SetActive(false);--取消申请
            self.enterBtn.gameObject:SetActive(true); -- 加入
        else
            self.canNotApplyText.gameObject:SetActive(false);--不可申请文字
            self.applyBtn.gameObject:SetActive(true);--申请
            self.cancelBtn.gameObject:SetActive(false);--取消申请
            self.enterBtn.gameObject:SetActive(false); -- 加入
        end
    end


    ----国站联盟审批数据状态
    --NATION_UNION_APPLY_SETTING = {
    --    CLOSE_APPLY = 0,--关闭申请
    --    ANY_PERSON = 1, --任何人申请即加入
    --    NEED_APPLY = 2,--申请审批
    --},

    --NationDefine.NATION_UNION_APPLY_SETTING.

    --self.applyBtn.gameObject:SetActive(singleData.state==1);--申请
    --self.cancelBtn.gameObject:SetActive(singleData.state==2);--取消申请
    --self.enterBtn.gameObject:SetActive(singleData.state==0); -- 加入
    --self.canNotApplyText.gameObject:SetActive(singleData.state==3);--不可申请文字
end

local function OnDisable(self)
    base.OnDisable(self)
    self.singleData = nil
end

local function OnDestroy(self)
    base.OnDestroy(self)
end

UINationEnterAlianceWrapItem.OnCreate = OnCreate
UINationEnterAlianceWrapItem.OnRefresh = OnRefresh
UINationEnterAlianceWrapItem.OnDestroy = OnDestroy
UINationEnterAlianceWrapItem.OnDisable = OnDisable
return UINationEnterAlianceWrapItem