---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LJ095.
--- DateTime: 2019/2/26 14:10
---
local MainCityCommonBtnManager = BaseClass("MainCityCommonBtnManager", Singleton)
local MainCityCommonBtnComponent = require "UI.UITestMain.View.MainCityCommonBtnComponent"

local common_bar_path = "UI/Prefabs/View/CommonBtnGroup.prefab";
local isFirst = true;

local MAIN_CITY_BTN_ENUM = {
    MAIN_CITY = 1, --主城
    GUO_ZHAN = 2, --国战
    EXPLORE = 3, --探险
}

local function RedRefresh(self)
    for i, v in pairs(self.maincityBtnHash) do
        if v ~= nil then
            v.barComponent:RefreshRedPoint()
        end
    end
end
--创建主城共用按钮
local function CreatMainCityCommonBtn(self, _parent, _windowName, holderSelf, func, _type, _initBtnState)
    local type = MAIN_CITY_BTN_ENUM.MAIN_CITY;
    if _type then
        type = _type;
    end
    if isFirst then
        self.maincityBtnHash = {};
        isFirst = false;
        self.bindFunc = Bind(self, RedRefresh)
        UIManager:GetInstance():AddListener(UIMessageNames.ON_RED_POINT_CHANGE, self.bindFunc)
    end
    if self.maincityBtnHash[_windowName] ~= nil then
        GameObjectPool:GetInstance():RecycleGameObject(common_bar_path, self.maincityBtnHash[_windowName].gameObj);
        self.maincityBtnHash[_windowName] = nil;
    end
    GameObjectPool:GetInstance():GetGameObjectAsync(common_bar_path, function(go)
        if not IsNull(go) then
            go.transform:SetParent(_parent.transform);
            go.transform:SetAsLastSibling();
            local commonBtnObj = MainCityCommonBtnComponent.New(holderSelf, go);
            self.maincityBtnHash[_windowName] = { gameObj = go, barComponent = commonBtnObj };
            commonBtnObj:OnCreate(_windowName, type, _initBtnState);
            commonBtnObj:RefreshRedPoint()
            local rectTrans = UIUtil.FindComponent(commonBtnObj.transform, typeof(CS.UnityEngine.RectTransform));
            rectTrans.localScale = Vector3.New(1, 1, 1);
            rectTrans.anchorMin = Vector2.New(0, 0);
            rectTrans.anchorMax = Vector2.New(1, 1);
            rectTrans.pivot = Vector2.New(0.5, 0.5);
            rectTrans.anchoredPosition3D = Vector3.New(0, 0, 0);
            rectTrans.sizeDelta = Vector2.New(0, 0);
            --新手引导事件
            self.maincityBtnHash[_windowName].barComponent:OnEnable();
            DataManager:GetInstance():Broadcast(DataMessageNames.UI_Guide_NeedEvent)
            if UnlockData:GetInstance().not_open_guide~=nil and #UnlockData:GetInstance().not_open_guide>0 then
                DataManager:GetInstance():Broadcast(DataMessageNames.UI_Guide_LockEvent)
            end
        end
    end)
end
--检测是否存在
local function CheckIsExist(self, _windowName)
    if self.maincityBtnHash[_windowName] ~= nil then
        DataManager:GetInstance():Broadcast(DataMessageNames.UI_Guide_NeedEvent)
    end
end

--设置按钮为初始状态
local function SetComInitial(self, _windowName)
    if self.maincityBtnHash[_windowName] ~= nil then
        self.maincityBtnHash[_windowName].barComponent:SetMainInitBtnState();
    end
end

--销毁资源条
local function DestroyMaincityBtn(self, _windowName)
    if self.maincityBtnHash[_windowName] then
        GameObjectPool:GetInstance():RecycleGameObject(common_bar_path, self.maincityBtnHash[_windowName].gameObj);
        if self.maincityBtnHash[_windowName].barComponent ~= nil then
            self.maincityBtnHash[_windowName].barComponent:OnDestroy()
        end
    end
    self.maincityBtnHash[_windowName] = nil;
end


MainCityCommonBtnManager.SetComInitial = SetComInitial;
MainCityCommonBtnManager.CreatMainCityCommonBtn = CreatMainCityCommonBtn;
MainCityCommonBtnManager.DestroyMaincityBtn = DestroyMaincityBtn;
MainCityCommonBtnManager.CheckIsExist = CheckIsExist
MainCityCommonBtnManager.MAIN_CITY_BTN_ENUM = MAIN_CITY_BTN_ENUM

return MainCityCommonBtnManager;