---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LJ095.
--- DateTime: 2019/2/20 15:06
---
local UIShopBuyItemModel = BaseClass("UIShopBuyItemModel", UIBaseModel);
local base = UIBaseModel;

local SingleGoodsData={
    id=-1,
    goodsName="",--物品名字
    icon="",--图标
    itemFrame="",--边框
    xlsxData=0,
    serverGoodsData=0,
    costIcon="",--花费图标
    costId=0,--花费的id
    desStr="",--描述
}
local goodsDataModel = DataClass("goodsDataModel",SingleGoodsData);
local function OnCreate(self)
    base.OnCreate(self)

end

local function OnEnable(self,goodsId)
    base.OnEnable(self)
    local shopGoodsXlsxData =  DataUtil.GetData("shop_goods");
    local singShopGoodsXlsx=shopGoodsXlsxData[goodsId];
    if singShopGoodsXlsx~=nil then
        self.singleGoodsData=goodsDataModel.New();
        self.singleGoodsData.id=goodsId
        self.singleGoodsData.goodsName=singShopGoodsXlsx.Name;
        local xlsxItemData=DataUtil.GetDataByIdAndType(singShopGoodsXlsx.Good.Id,14,singShopGoodsXlsx.Good.Val);
        self.singleGoodsData.icon=xlsxItemData.icon;
        self.singleGoodsData.itemFrame= SpriteDefine:GetItemQualityFrameByType(xlsxItemData.quality);
        self.singleGoodsData.xlsxData=singShopGoodsXlsx;

        self.singleGoodsData.serverGoodsData=ShopData:GetInstance():GetShopInfoById(self.singleGoodsData.id);
        self.singleGoodsData.desStr=xlsxItemData.des;
        local costXlsxItemData=DataUtil.GetDataByIdAndType(singShopGoodsXlsx.CoinType,14);
        self.singleGoodsData.costIcon=costXlsxItemData.icon;
        self.singleGoodsData.costId=costXlsxItemData.id;
    else
        Logger.Log("goodsId:"..goodsId)
    end


end

local function UpdateBuyTimes(self)
    if self.singleGoodsData ~= nil then
        self.singleGoodsData.serverGoodsData=ShopData:GetInstance():GetShopInfoById(self.singleGoodsData.id);
    end
    self:UIBroadcast(UIMessageNames.UISHOP_BUY_UPDATE)
end

-- 监听
local function OnAddListener(self)
    base.OnAddListener(self)
    --添加监听
    self:AddDataListener(DataMessageNames.ON_SHOP_INFO_END,UpdateBuyTimes)
end

local function OnRemoveListener(self)
    base.OnRemoveListener(self)
    -- 移除监听
    self:RemoveDataListener(DataMessageNames.ON_SHOP_INFO_END,UpdateBuyTimes)
end

UIShopBuyItemModel.OnAddListener = OnAddListener
UIShopBuyItemModel.OnRemoveListener = OnRemoveListener
UIShopBuyItemModel.OnCreate=OnCreate;
UIShopBuyItemModel.OnEnable=OnEnable;
return UIShopBuyItemModel