---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/10/31 20:04
---
local UIWBMainEventPanel = BaseClass("UIWBMainEventPanel", UIWrapComponent)
local base = UIWrapComponent

local element_event_info = DataUtil.GetData("mu_p_boss_element")

local function SetActive(self, isActive)
    self.transform.gameObject:SetActive(isActive)
end

local function ClickEventChoose(self, index)
    DRBossData:GetInstance():SendExploreEvent(self.teamId, index)
end

local function OnCreate(self)
    base.OnCreate(self)
    self.maskBtn = self:AddComponent(UIButton, "mask");
    self.maskBtn:SetOnClick(function ()
        LJAudioManger:GetInstance():PlayVoice("UI_CommonClick");
        SetActive(self, false)
    end)
    self.exitBtn = self:AddComponent(UIButton, "ParentLayout/exitBtn");
    self.exitBtn:SetOnClick(function ()
        LJAudioManger:GetInstance():PlayVoice("UI_CommonClick");
        SetActive(self, false)
    end)
    self.eventIcon = self:AddComponent(UIImage, "ParentLayout/eventIcon",AtlasConfig.DynamicTex)
    self.titleText = self:AddComponent(UIText, "ParentLayout/titleText")
    self.desText = self:AddComponent(UIText, "ParentLayout/eventDesText")
    self.chooseText = {}
    for i = 1, 3 do
        self.chooseText[i] = self:AddComponent(UIText, "ParentLayout/chooseText"..i)
        local btn = self:AddComponent(UIButton, "ParentLayout/chooseText"..i)
        btn:SetOnClick(function ()
            LJAudioManger:GetInstance():PlayVoice("UI_CommonClick");
            ClickEventChoose(self, i)
        end)
    end
end

-- 组件被复用时回调该函数，执行组件的刷新
local function OnRefresh(self, teamId, eventId)
    self.data = element_event_info[eventId]
    self.teamId = teamId
    if self.data == nil then
        return
    end
    self.titleText:SetText("事件："..self.data.ElementName)
    self.eventIcon:SetSpriteName(self.data.ElementIcon)
    self.desText:SetText(string.format(self.data.ElementEventDes,"队伍"..teamId))
    for i = 1, 3 do
        if self.data.EventOptionDes[i] ~= nil then
            self.chooseText[i].gameObject:SetActive(true)
            if self.data.EventOption ~= nil then
                if self.data.EventOption[i].Param1 ~= nil then
                    if self.data.EventOption[i].Param2 ~= nil then
                        self.chooseText[i]:SetText(string.format(self.data.EventOptionDes[i],self.data.EventOption[i].Param1,self.data.EventOption[i].Param2))
                    else
                        self.chooseText[i]:SetText(string.format(self.data.EventOptionDes[i],self.data.EventOption[i].Param1))
                    end
                else
                    self.chooseText[i]:SetText(self.data.EventOptionDes[i])
                end
            else
                self.chooseText[i]:SetText(self.data.EventOptionDes[i])
            end
        else
            self.chooseText[i].gameObject:SetActive(false)
        end
    end

    SetActive(self, true)
end

UIWBMainEventPanel.OnCreate = OnCreate
UIWBMainEventPanel.OnRefresh = OnRefresh
UIWBMainEventPanel.SetActive = SetActive

return UIWBMainEventPanel