---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guoyu.
--- DateTime: 2019/3/11 15:22
---
local ClientRankDataCenter=BaseClass("ClientRankDataCenter",Singleton)



local RankDataBase={
    Type1=1,--大类型(1卢花古楼，2竞技场...)
    Type2=1,--小类型(2-1白银竞技场，2-2黄金竞技场.2-1卢花古楼...)
    rankItemDataList={},
}

local LhglRankItemData=BaseClass("LhglRankItemData",RankDataBase)

LhglRankItemData.__init=function(self)
    self.paiming=1
    self.frameIcon=0
    self.headIcon=0
    self.name=""
    self.cengShu=""
end


local ArenaRankItemData=BaseClass("ArenaRankItemData")
ArenaRankItemData.__init=function(self)
    self.paiming=0
    self.frameIcon=0
    self.headIcon=0
    self.name=""
    self.score=0
end


local LuglRankData=BaseClass("LuglRankData",RankDataBase)
LuglRankData.__init=function(self)
    self.myPaiming=0
    self.myFramdIcon=0
    self.myHeadIcon=0
    self.myName=""
    self.myCengShu=0
end


local ArenaRankData=BaseClass("ArenaRankData",RankDataBase)




local function __init(self)
    self.randDataList={}--排行榜数据
end

local function ParseReedRankMsg(self,Packages,type1Index,type2Index)
    local rankData=self:GetRankDataByType(type1Index,type2Index)
    if rankData==nil then
        rankData=LuglRankData.New()
        rankData.Type1=type1Index
        rankData.Type2=type2Index
        rankData.rankItemDataList={}
    else
        rankData.rankItemDataList={}
    end
    if not Packages.reedRank._is_null and table.ProtoRepeatedCount(Packages.reedRank)>0 then
        for k,v in ipairs(Packages.reedRank) do
            local ItemData=LhglRankItemData.New()
            ItemData.paiming=v.rank
            ItemData.frameIcon=v.frame
            ItemData.head=v.head
            ItemData.name=v.name
            ItemData.cengShu=v.tower
            table.insert(rankData.rankItemDataList,ItemData)
        end
    end
    if not Packages.selfReedRank then
        self.myPaiming=Packages.selfReedRank.rank
        self.myFramdIcon=Packages.selfReedRank.frame
        self.myHeadIcon=Packages.selfReedRank.head
        self.myName=Packages.selfReedRank.name
        self.myCengShu=Packages.selfReedRank.cengShu
    end
    DataManager:GetInstance():Broadcast(DataMessageNames.ON_RECIVE_RANK_DATA,rankData)
end


local function ParseArenaRankMsg(self,Packages,type1Index,type2Index)
    local rankData=self:GetRankDataByType(type1Index,type2Index)
    if rankData==nil then
        rankData=ArenaRankData.New()
        rankData.Type1=type1Index
        rankData.Type2=type2Index
        rankData.rankItemDataList={}
    else
        rankData.rankItemDataList={}
    end
    if not Packages.rankList._is_null and table.ProtoRepeatedCount(Packages.rankList)>0 then
        for k,v in ipairs(Packages.rankList) do
            local ItemData=ArenaRankItemData.New()
            ItemData.paiming=Mathf.Floor(v.rank)
            ItemData.frameIcon=v.framd
            ItemData.headIcon=v.head
            ItemData.name=v.name
            ItemData.score=Mathf.Floor(v.score)
            table.insert(rankData.rankItemDataList,ItemData)
        end
    end
    DataManager:GetInstance():Broadcast(DataMessageNames.ON_RECIVE_RANK_DATA,rankData)
end






local function GetRankDataByType(self,type1Index,type2Index)
    local randData=nil
    for k,v in pairs(self.randDataList) do
        if v.Type1==type1Index and v.Type2==type2Index then
            randData=v
            break
        end
    end
    return randData
end




ClientRankDataCenter.__init=__init
ClientRankDataCenter.ParseReedRankMsg=ParseReedRankMsg
ClientRankDataCenter.ParseArenaRankMsg=ParseArenaRankMsg
ClientRankDataCenter.GetRankDataByType=GetRankDataByType
return ClientRankDataCenter