---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/9/10 15:33
---
local TongLingData = BaseClass("TongLingData", Singleton)
local tongling_group_data = DataUtil.GetData("card_channeling")
local function __init(self)
    self.have_card_list={}
end
local function GetTongLingData(self)

    local state,type,des= UnlockData:GetInstance():GetLockDataState(305)
    if not state then
        return
    end
    if self.have_send then
        Logger.LogError("已经请求过通灵")
        return
    else
        self.have_send=true
    end
    local msdId = MsgIDDefine.PBCARD_ALL_CARD_CHANNELING_REQUEST
    NetManager:GetInstance():SendMessage(msdId,nil,function(msg_obj)
        if msg_obj.OpCode ~= 0 then
            Logger.Log("OnRecvPveStart出错了~")
            UISpecial:GetInstance():UITipText(msg_obj.Packages.msg)
            return
        end
        self.have_card_list={}
        if msg_obj.Packages.channelingId then
            for i = 1, #msg_obj.Packages.channelingId do
                self.have_card_list[i]=msg_obj.Packages.channelingId[i]
            end
        end
    end)
end
local function UpdateTongLingData(self,data)
    local _index= #self.have_card_list
    self.have_card_list[_index+1]=data
end
local function CheckTongLingRed(self)
    RedPointData:GetInstance():UpdateCardRedState(RedPointData:GetInstance().RedName.TongLing_Red,false)
    for  value,data in pairs(tongling_group_data) do
        local NoThisCard=true
        for n = 1, #self.have_card_list do
            if data.ID==self.have_card_list[n] then
                NoThisCard=false
                break
            end
        end
        if data~=nil and NoThisCard then
            local cansethave=true
            if data.NeedCardIds~=nil then
                --判断有没有   有的话看条件
                for j = 1, #data.NeedCardIds do
                    local CardDataInfo =CardData:GetInstance():GetCardDataById(data.NeedCardIds[j])
                    if CardDataInfo~=nil then
                        for m = 1, #data.CardCondition[j] do
                            if data.CardCondition[j][m].Con==1 then
                                --判断物品等级
                                if  CardDataInfo.level<data.CardCondition[j][m].Param then
                                    --不满足条件
                                    cansethave=false
                                    break
                                end
                            elseif data.CardCondition[j][m].Con==2 then
                                --判断物品星
                                if  CardDataInfo.starlv<data.CardCondition[j][m].Param  then
                                    --不满足条件
                                    cansethave=false
                                    break
                                end
                            end
                        end
                    else
                        cansethave=false
                        break
                    end
                end
            end
            if cansethave then
                --满足条件
                RedPointData:GetInstance():UpdateCardRedState(RedPointData:GetInstance().RedName.TongLing_Red,true)
                break
            end
        end
    end
end
local function __delete(self)
    self.have_card_list={}
end
TongLingData.__init = __init
TongLingData.GetTongLingData = GetTongLingData
TongLingData.UpdateTongLingData = UpdateTongLingData
TongLingData.CheckTongLingRed = CheckTongLingRed
TongLingData.__delete =  __delete
return TongLingData