---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LJ095.
--- DateTime: 2019/6/15 14:41
---

local ExploreCardItem = BaseClass("ExploreCardItem", UIWrapComponent)
local base = UIWrapComponent



local frame_path="CardHead/Frame";
local icon_path="CardHead/IconImg";
local crystal_bg_path="CardHead/Crystal";
local crystal_num_path="CardHead/Crystal/CrystalNum";
local quality_img_path="CardHead/QualityImg";
local lv_text_path="CardHead/LevelText";
local btn_path="CardHead";
local mask_path="CardHead/selectMask";

local function OnCreate(self)
    base.OnCreate(self)
    self.frame=self:AddComponent(UIImage,frame_path,AtlasConfig.DynamicTex);
    self.icon=self:AddComponent(UIImage,icon_path,AtlasConfig.DynamicTex);
    self.crystalBg=self:AddComponent(UIImage,crystal_bg_path,AtlasConfig.DynamicTex);
    self.crystalNum=self:AddComponent(UIText,crystal_num_path);
    self.qualityImg=self:AddComponent(UIImage,quality_img_path,AtlasConfig.DynamicTex);
    self.lvText=self:AddComponent(UIText,lv_text_path);
    self.iconBtn=self:AddComponent(UIButton,btn_path);
    self.iconBtn:SetOnClick(function()
        if self.view:GetCurSelectHeroCount()<self.view.model.hangUpTeamNum or self.view.cardList[self.realIndex+1].isSelect then
            self.view.cardList[self.realIndex+1].isSelect=not self.view.cardList[self.realIndex+1].isSelect;
            self.maskObj.gameObject:SetActive(self.view.cardList[self.realIndex+1].isSelect);
            local upOrDown=self.view.cardList[self.realIndex+1].isSelect and 1 or 0;
            self.view:SetHeroUpOrDown(upOrDown,self.view.cardList[self.realIndex+1].cardData,self.realIndex+1);
        else
            UISpecial:GetInstance():UITipText(string.format("当前最多可派遣%s个角色",self.view.model.hangUpTeamNum));
        end
    end)
    self.maskObj=UIUtil.FindTrans(self.transform,mask_path);
    self.starGroup=self:AddComponent(UIBaseContainer,"CardHead/Star");
    self.starList={};
    local starCount=self.starGroup.transform.childCount;
    for i = 0, starCount-1 do
        local singleStarImg=self.starGroup:AddComponent(UIImage,i,AtlasConfig.DynamicTex);
        table.insert(self.starList,singleStarImg);
    end

end

-- 组件被复用时回调该函数，执行组件的刷新
local function OnRefresh(self, real_index, check)
    self.realIndex=real_index;
    local cardData=self.view.cardList[real_index+1].cardData;
    self.frame:SetSpriteName(SpriteDefine:GetCardTopFrameByQuality(cardData.quality));
    self.icon:SetSpriteName(cardData.icon);
    self.crystalBg.transform.gameObject:SetActive(cardData.type==2)
    self.crystalBg:SetSpriteName(SpriteDefine:GetCrystalIconByType(cardData.crystalType));
    self.crystalNum:SetText(cardData.callCost);
    self.qualityImg:SetSpriteName(SpriteDefine:GetQuaIconByType(cardData.quality));
    self.lvText:SetText(string.format("Lv.%s",math.floor(cardData.level)));
    local isSelect=self.view.cardList[real_index+1].isSelect
    if isSelect then

    end
    self.maskObj.gameObject:SetActive(isSelect);
    UIUtil.SetHeroStar(cardData.starlv,self.starList);
end


ExploreCardItem.OnCreate = OnCreate
ExploreCardItem.OnRefresh = OnRefresh
return ExploreCardItem