---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LJ095.
--- DateTime: 2019/10/17 17:04
---

local UILyztSingleStoryItem = BaseClass("UILyztSingleStoryItem", UIWrapComponent)
local base = UIWrapComponent

local title_name_path="titleName";
local red_point_path="RedPointImg";


--设置选中
local function SetSelectImg(self)
    self.view.selectImg.transform.gameObject:SetActive(true);
    self.view.selectImg.transform:SetParent(self.transform);
    self.view.selectImg.transform.localScale=Vector2.one;
    self.view.selectImg.transform.localPosition=Vector2.New(0,6);
    self.view.selectImg.transform:SetAsFirstSibling();
end

local function OnCreate(self)
    base.OnCreate(self)
    -- 初始化各个组件
    self.titleName=self:AddComponent(UIText,title_name_path);
    self.redPoint=UIUtil.FindTrans(self.transform,red_point_path);
    self.selfBtn=self:AddComponent(UIButton,"");
    self.selfBtn:SetOnClick(function()
        self.view:ShowStoryContet(self.realIndex);
        SetSelectImg(self);
    end)
end

local function OnRefresh(self, real_index)
    self.realIndex=real_index+1;

    if self.realIndex==self.view.selectIndex then
        SetSelectImg(self);
    else
        if UIUtil.FindTrans(self.transform,"Slect") then
            self.view.selectImg.transform.gameObject:SetActive(false);
        end
    end

    self.titleName:SetText(self.view.model.storyList[self.realIndex].title);
end

UILyztSingleStoryItem.OnCreate = OnCreate
UILyztSingleStoryItem.OnRefresh = OnRefresh
return UILyztSingleStoryItem